import type { Metadata } from "next";
import PolicyPage, { type PolicySection } from "@/components/PolicyPage";
import { buildMetadata } from "@/lib/seo";

export const metadata: Metadata = buildMetadata({ title: "Privacy Policy", description: "How Lumyn collects, uses, stores, and shares personal information.", path: "/privacy" });

const sections: PolicySection[] = [
  { title: "Scope", paragraphs: [<>This Privacy Policy explains how Lumyn Product Studio processes personal information when you visit our website, contact us, subscribe to communications, create a Lumyn Academy account, purchase a plan, or use our learning and mentorship services.</>] },
  { title: "Information we collect", bullets: [<>Account information such as your name, email address, authentication identifier, and profile details.</>, <>Learning information such as course requests, skill level, goals, generated courses, progress, quiz attempts, assignments, projects, tutor conversations, and certificates.</>, <>Transaction information such as plan, amount, currency, payment reference, payment status, customer code, and subscription status. Lumyn does not store complete card details.</>, <>Messages, mentorship applications, support requests, newsletter preferences, and other information you choose to provide.</>, <>Technical information such as device, browser, approximate location, pages visited, referral information, cookies, and analytics events.</>] },
  { title: "How we use information", bullets: [<>Provide authentication, personalized courses, AI tutoring, assessments, progress records, mentorship, certificates, and customer support.</>, <>Initialize and verify payments, administer subscriptions, prevent fraud, and maintain transaction records.</>, <>Send service messages, receipts, learning updates, and marketing communications where permitted.</>, <>Secure, troubleshoot, measure, and improve our website and services.</>, <>Comply with legal obligations, enforce our terms, and protect users, Lumyn, and the public.</>] },
  { title: "Payments", paragraphs: [<>Payments are processed by Paystack. When you pay, Paystack collects and processes payment details under its own privacy terms. Lumyn receives transaction and subscription information needed to verify payment and provide access, but we do not receive or store your complete card number or security code.</>] },
  { title: "AI and service providers", paragraphs: [<>To generate courses, tutor responses, and submission feedback, relevant prompts and learning context may be sent to our configured AI service providers. Do not submit secrets, sensitive personal information, or confidential third-party material to AI features.</>], bullets: [<>We also use providers for authentication, cloud databases, email delivery, analytics, hosting, and payment processing.</>, <>Providers may process information in other countries and are permitted to use it only to deliver contracted services or as required by law.</>] },
  { title: "Cookies and analytics", paragraphs: [<>We use necessary browser storage for authentication, preferences, security, and theme settings. We may use analytics tools to understand aggregate product usage and improve performance. You can limit optional cookies through browser settings, although some functionality may be affected.</>] },
  { title: "Sharing", paragraphs: [<>We do not sell personal information. We share it only with service providers, professional advisers, mentors where necessary to deliver mentorship, authorities when legally required, or a successor in connection with a merger, financing, acquisition, or sale of assets.</>] },
  { title: "Retention and security", paragraphs: [<>We retain information for as long as needed to provide the service, maintain legitimate business and financial records, resolve disputes, and meet legal obligations. Retention periods vary by data type. We use reasonable administrative and technical safeguards, but no internet service can guarantee absolute security.</>] },
  { title: "Your choices and rights", bullets: [<>You may update account information, cancel subscription renewal, unsubscribe from marketing messages, or request access, correction, deletion, restriction, or export of personal information where applicable.</>, <>Some records may be retained where required for payment, fraud prevention, legal compliance, or legitimate dispute resolution.</>, <>To make a privacy request, contact us using the details below. We may verify your identity before completing the request.</>] },
  { title: "Children and changes", paragraphs: [<>Lumyn is not intentionally directed to children who cannot lawfully consent to data processing in their location. We may update this policy as our services or legal duties change. Material updates will be reflected by the date on this page and communicated where appropriate.</>] },
  { title: "Contact", paragraphs: [<>Privacy questions and requests may be submitted through our <a href="/contact" className="font-semibold text-[#6c5ce7] underline underline-offset-4 dark:text-[#b9b1ff]">contact page</a> or sent to <a href="mailto:hello@lumynhq.studio" className="font-semibold text-[#6c5ce7] underline underline-offset-4 dark:text-[#b9b1ff]">hello@lumynhq.studio</a>.</>] },
];

export default function PrivacyPage() { return <PolicyPage eyebrow="Privacy" title="Privacy Policy" summary="What we collect, why we use it, which providers help us operate, and the choices available to you." updated="22 June 2026" sections={sections} />; }
