import type { Metadata } from "next";
import PolicyPage, { type PolicySection } from "@/components/PolicyPage";
import { buildMetadata } from "@/lib/seo";

export const metadata: Metadata = buildMetadata({ title: "Privacy Policy", description: "How Lumyn collects, uses, stores, and shares personal information.", path: "/privacy" });

const sections: PolicySection[] = [
  { title: "Scope", paragraphs: [<>This Privacy Policy explains how Lumyn Product Studio processes personal information when you visit our website, contact us, subscribe to communications, create a Lumyn Academy account, subscribe to Astra, buy or sell a course on the Lumyn Academy Marketplace, or use our learning services.</>] },
  { title: "Information we collect", bullets: [<>Account information such as your name, email address, authentication identifier, and profile details.</>, <>Learning information such as enrollments, progress, quiz attempts, assignments, projects, tutor conversations, and certificates.</>, <>Transaction information such as subscription status, amount, currency, payment reference, payment status, and diamonds balance. Lumyn does not store complete card details.</>, <>If you become a Marketplace creator: your legal name, a government-issued identification type and number, and payout bank details (bank name and account number), collected to verify your identity and pay your earnings. Government ID and bank account numbers are encrypted at rest.</>, <>If you upload course video as a creator, the video file itself and metadata about it (title, duration, processing status).</>, <>Messages, support requests, newsletter preferences, and other information you choose to provide.</>, <>Technical information such as device, browser, approximate location, pages visited, referral information, cookies, and analytics events.</>] },
  { title: "How we use information", bullets: [<>Provide authentication, course access, AI tutoring, assessments, progress records, certificates, and customer support.</>, <>Initialize and verify payments, maintain diamonds balances, prevent fraud, and maintain transaction records.</>, <>Manually verify a creator's identity before their first Marketplace course is published, calculate and route creator earnings, and administer the Marketplace.</>, <>Send service messages, receipts, learning updates, and marketing communications where permitted.</>, <>Secure, troubleshoot, measure, and improve our website and services.</>, <>Comply with legal obligations, enforce our terms, and protect users, Lumyn, and the public.</>] },
  { title: "Payments", paragraphs: [<>Astra subscription and certificate-unlock payments are processed by Flutterwave. Marketplace course purchases and the one-time creator listing fee are processed by Paystack, which also pays creators their share of each sale directly to their connected bank account. When you pay, our payment processors collect and process payment details under their own privacy terms. Lumyn receives transaction information needed to verify payment and activate the relevant access, but we do not receive or store your complete card number or security code.</>] },
  { title: "AI and service providers", paragraphs: [<>To provide tutor responses and submission feedback, relevant prompts and learning context may be sent to our configured AI service providers. Do not submit secrets, sensitive personal information, or confidential third-party material to AI features.</>], bullets: [<>We also use providers for authentication, cloud databases, email delivery, analytics, hosting, video storage and streaming (Bunny Stream, for creator-uploaded course video), and payment processing.</>, <>Providers may process information in other countries and are permitted to use it only to deliver contracted services or as required by law.</>] },
  { title: "Cookies and analytics", paragraphs: [<>We use necessary browser storage for authentication, preferences, security, and theme settings. We may use analytics tools to understand aggregate product usage and improve performance. You can limit optional cookies through browser settings, although some functionality may be affected.</>] },
  { title: "Sharing", paragraphs: [<>We do not sell personal information. We share it only with service providers, professional advisers, authorities when legally required, or a successor in connection with a merger, financing, acquisition, or sale of assets. A creator's government ID number, ID type, and bank account details are used only by Lumyn for verification and by our payment processor to route payouts — they are never shared with students or other creators. When you buy a Marketplace course, the creator does not receive your payment details; they see only that a sale occurred.</>] },
  { title: "Retention and security", paragraphs: [<>We retain information for as long as needed to provide the service, maintain legitimate business and financial records, resolve disputes, and meet legal obligations. Retention periods vary by data type. Sensitive Marketplace information — creator government ID numbers and bank account numbers — is encrypted at rest. We use reasonable administrative and technical safeguards, but no internet service can guarantee absolute security.</>] },
  { title: "Your choices and rights", bullets: [<>You may update account information, unsubscribe from marketing messages, or request access, correction, deletion, restriction, or export of personal information where applicable.</>, <>Some records may be retained where required for payment, fraud prevention, legal compliance, or legitimate dispute resolution — including a creator's verification records, which we keep for as long as their Marketplace account is active and as required by law afterward.</>, <>To make a privacy request, contact us using the details below. We may verify your identity before completing the request.</>] },
  { title: "Children and changes", paragraphs: [<>Lumyn is not intentionally directed to children who cannot lawfully consent to data processing in their location. We may update this policy as our services or legal duties change. Material updates will be reflected by the date on this page and communicated where appropriate.</>] },
  { title: "Contact", paragraphs: [<>Privacy questions and requests may be submitted through our <a href="/contact" className="font-semibold text-[#6c5ce7] underline underline-offset-4 dark:text-[#b9b1ff]">contact page</a> or sent to <a href="mailto:hello@lumynhq.studio" className="font-semibold text-[#6c5ce7] underline underline-offset-4 dark:text-[#b9b1ff]">hello@lumynhq.studio</a>.</>] },
];

export default function PrivacyPage() { return <PolicyPage eyebrow="Privacy" title="Privacy Policy" summary="What we collect, why we use it, which providers help us operate, and the choices available to you." updated="13 September 2026" sections={sections} />; }
