import type { Metadata } from "next";
import PolicyPage, { type PolicySection } from "@/components/PolicyPage";
import { buildMetadata } from "@/lib/seo";

export const metadata: Metadata = buildMetadata({ title: "Terms and Conditions", description: "Terms governing Lumyn products, Lumyn Academy, payments, and use of the website.", path: "/terms" });

const sections: PolicySection[] = [
  { title: "About these terms", paragraphs: [<>These Terms and Conditions govern your use of the Lumyn website, Lumyn Academy, and related services operated by Lumyn Product Studio (“Lumyn”, “we”, “us”, or “our”). By creating an account, subscribing to a paid feature, or using a service, you agree to these terms.</>] },
  { title: "Accounts and eligibility", bullets: [<>You must provide accurate account and contact information and keep your sign-in credentials secure.</>, <>You are responsible for activity performed through your account. Notify us promptly if you suspect unauthorized access.</>, <>Users under the age required to enter a binding contract in their location must have permission from a parent or legal guardian.</>] },
  { title: "Academy services", paragraphs: [<>Lumyn Academy provides structured courses, quizzes, assignments, project feedback, progress tracking, certificates, and an AI tutor named Astra. AI tutor responses and AI-assessed submission feedback may contain errors and should be checked against reliable sources, especially before using them in production or making important decisions.</>], bullets: [<>Course lessons, quizzes, assignments, and projects are free to access for every learner. The AI tutor requires an active monthly subscription unless Lumyn grants an account exemption.</>, <>Certificates reflect completion of the applicable Lumyn learning requirements; they are not an accredited degree or professional licence.</>] },
  { title: "Creator Marketplace", paragraphs: [<>The Lumyn Academy Marketplace lets any account holder ("creator") upload and sell their own courses to other students. Becoming a creator and listing a course is subject to all of the following, in addition to the rest of these terms.</>], bullets: [
    <>Before your first course can be published, you must submit accurate identity information (your legal name and a government-issued ID) and payout bank details, and pay a one-time, non-refundable listing fee. Lumyn manually reviews this information; we may decline to approve a creator or a course at our discretion.</>,
    <>Every course you submit must be your own original work. You represent and warrant that you own all rights to your course content, or hold explicit permission to use every piece of included material, and that it does not infringe any copyright, trademark, or other right of a third party.</>,
    <>You agree to indemnify and hold Lumyn harmless from any claim, loss, or expense arising from a breach of that warranty, including claims that your course content infringes someone else's rights.</>,
    <>Course video and audio must be clear and watchable, and course content must substantively deliver on what it promises. Lumyn may reject, unpublish, or remove any course that does not meet these standards, contains prohibited or infringing material, or otherwise violates these terms, and may suspend or terminate a creator's ability to sell for repeated or serious violations.</>,
    <>By submitting a course, you grant Lumyn a licence to host, store, encode, stream, and display it (including applying a viewer-identifying watermark during playback) solely to operate and secure the Marketplace. You keep ownership of your content.</>,
    <>Lumyn retains a percentage of each sale — shown to you in Creator Studio before you list a course — and pays the remainder to your connected payout account. Payouts are processed by Paystack on its own settlement schedule, which Lumyn does not set and is not responsible for delays to.</>,
    <>Purchasing a course grants the buyer a personal, non-transferable licence to view it for their own learning. Course content may not be downloaded outside the platform, redistributed, shared, resold, or publicly performed. Access is protected by signed, expiring playback links and a viewer watermark; attempting to circumvent these protections is a violation of these terms.</>,
  ] },
  { title: "Pricing and billing", paragraphs: [<>The AI tutor subscription, certificate unlocks, Marketplace course purchases, and the creator listing fee are priced and displayed before checkout.</>], bullets: [<>Subscription charges and certificate unlock payments are processed through Flutterwave. Marketplace course purchases and the creator listing fee are processed through Paystack.</>, <>By completing checkout, you authorize the applicable payment processor and Lumyn to process the displayed amount.</>, <>Your bank or payment provider may apply conversion, card, or cross-border charges that Lumyn does not control.</>] },
  { title: "Refunds", paragraphs: [<>Refund eligibility and the request process are described in our <a href="/refund-policy" className="font-semibold text-[#6c5ce7] underline underline-offset-4 dark:text-[#b9b1ff]">Refund Policy</a>, which forms part of these terms and applies to Marketplace course purchases and the creator listing fee as well as Academy subscriptions and certificates.</>] },
  { title: "Acceptable use", bullets: [<>Do not misuse the service, bypass access controls, interfere with its operation, scrape protected content, or attempt unauthorized access.</>, <>Do not use the AI tutor or submission tools to distribute unlawful, abusive, deceptive, infringing, or malicious material.</>, <>Do not resell, publish, or systematically reproduce Lumyn's courses, curriculum, or other materials as a competing service without written permission.</>] },
  { title: "Your content and our materials", paragraphs: [<>You retain ownership of original material you submit. You give Lumyn a limited licence to host, process, and evaluate that material solely to operate and improve the service. Lumyn owns its brand, interface, platform code, curriculum, and other proprietary materials. AI tutor responses and AI-assessed feedback are provided for your personal educational use, subject to applicable law and third-party rights.</>] },
  { title: "Availability and changes", paragraphs: [<>We work to keep the services available but do not guarantee uninterrupted operation. We may change features, providers, or reasonable usage limits to maintain security, quality, and sustainability. Material changes affecting paid service will be communicated where reasonably possible.</>] },
  { title: "Disclaimers and liability", paragraphs: [<>The services are provided on an “as available” basis. Educational content and AI feedback do not guarantee employment, certification by another institution, earnings, or a particular outcome. To the fullest extent permitted by law, Lumyn is not liable for indirect or consequential losses. Our aggregate liability relating to a paid service will not exceed the amount you paid Lumyn for that service during the three months preceding the event giving rise to the claim.</>] },
  { title: "Termination and governing law", paragraphs: [<>You may stop using the service at any time. We may suspend or terminate access for material breach, fraud, abuse, payment failure, or security risk. These terms are governed by the laws of the Federal Republic of Nigeria, without limiting mandatory consumer rights that apply where you live.</>] },
  { title: "Contact", paragraphs: [<>Questions about these terms may be sent through our <a href="/contact" className="font-semibold text-[#6c5ce7] underline underline-offset-4 dark:text-[#b9b1ff]">contact page</a> or by email to <a href="mailto:hello@lumynhq.studio" className="font-semibold text-[#6c5ce7] underline underline-offset-4 dark:text-[#b9b1ff]">hello@lumynhq.studio</a>.</>] },
];

export default function TermsPage() { return <PolicyPage eyebrow="Legal" title="Terms and Conditions" summary="The rules and responsibilities that keep Lumyn’s products, learning services, and payments clear and fair." updated="13 September 2026" sections={sections} />; }
