import type { Metadata } from "next";
import PolicyPage, { type PolicySection } from "@/components/PolicyPage";
import { buildMetadata } from "@/lib/seo";

export const metadata: Metadata = buildMetadata({ title: "Terms and Conditions", description: "Terms governing Lumyn products, Lumyn Academy, payments, and use of the website.", path: "/terms" });

const sections: PolicySection[] = [
  { title: "About these terms", paragraphs: [<>These Terms and Conditions govern your use of the Lumyn website, Lumyn Academy, and related services operated by Lumyn Product Studio (“Lumyn”, “we”, “us”, or “our”). By creating an account, subscribing to a paid feature, or using a service, you agree to these terms.</>] },
  { title: "Accounts and eligibility", bullets: [<>You must provide accurate account and contact information and keep your sign-in credentials secure.</>, <>You are responsible for activity performed through your account. Notify us promptly if you suspect unauthorized access.</>, <>Users under the age required to enter a binding contract in their location must have permission from a parent or legal guardian.</>] },
  { title: "Academy services", paragraphs: [<>Lumyn Academy provides structured courses, quizzes, assignments, project feedback, progress tracking, certificates, and an AI tutor named Astra. AI tutor responses and AI-assessed submission feedback may contain errors and should be checked against reliable sources, especially before using them in production or making important decisions.</>], bullets: [<>Course lessons, quizzes, assignments, and projects are free to access for every learner. The AI tutor requires an active monthly subscription unless Lumyn grants an account exemption.</>, <>Certificates reflect completion of the applicable Lumyn learning requirements; they are not an accredited degree or professional licence.</>] },
  { title: "Pricing and billing", paragraphs: [<>The AI tutor subscription and certificate unlocks are priced and displayed before checkout.</>], bullets: [<>Subscription charges and certificate unlock payments are processed through Flutterwave.</>, <>By completing checkout, you authorize Flutterwave and Lumyn to process the displayed amount.</>, <>Your bank or payment provider may apply conversion, card, or cross-border charges that Lumyn does not control.</>] },
  { title: "Refunds", paragraphs: [<>Refund eligibility and the request process are described in our <a href="/refund-policy" className="font-semibold text-[#6c5ce7] underline underline-offset-4 dark:text-[#b9b1ff]">Refund Policy</a>, which forms part of these terms.</>] },
  { title: "Acceptable use", bullets: [<>Do not misuse the service, bypass access controls, interfere with its operation, scrape protected content, or attempt unauthorized access.</>, <>Do not use the AI tutor or submission tools to distribute unlawful, abusive, deceptive, infringing, or malicious material.</>, <>Do not resell, publish, or systematically reproduce Lumyn's courses, curriculum, or other materials as a competing service without written permission.</>] },
  { title: "Your content and our materials", paragraphs: [<>You retain ownership of original material you submit. You give Lumyn a limited licence to host, process, and evaluate that material solely to operate and improve the service. Lumyn owns its brand, interface, platform code, curriculum, and other proprietary materials. AI tutor responses and AI-assessed feedback are provided for your personal educational use, subject to applicable law and third-party rights.</>] },
  { title: "Availability and changes", paragraphs: [<>We work to keep the services available but do not guarantee uninterrupted operation. We may change features, providers, or reasonable usage limits to maintain security, quality, and sustainability. Material changes affecting paid service will be communicated where reasonably possible.</>] },
  { title: "Disclaimers and liability", paragraphs: [<>The services are provided on an “as available” basis. Educational content and AI feedback do not guarantee employment, certification by another institution, earnings, or a particular outcome. To the fullest extent permitted by law, Lumyn is not liable for indirect or consequential losses. Our aggregate liability relating to a paid service will not exceed the amount you paid Lumyn for that service during the three months preceding the event giving rise to the claim.</>] },
  { title: "Termination and governing law", paragraphs: [<>You may stop using the service at any time. We may suspend or terminate access for material breach, fraud, abuse, payment failure, or security risk. These terms are governed by the laws of the Federal Republic of Nigeria, without limiting mandatory consumer rights that apply where you live.</>] },
  { title: "Contact", paragraphs: [<>Questions about these terms may be sent through our <a href="/contact" className="font-semibold text-[#6c5ce7] underline underline-offset-4 dark:text-[#b9b1ff]">contact page</a> or by email to <a href="mailto:hello@lumynhq.studio" className="font-semibold text-[#6c5ce7] underline underline-offset-4 dark:text-[#b9b1ff]">hello@lumynhq.studio</a>.</>] },
];

export default function TermsPage() { return <PolicyPage eyebrow="Legal" title="Terms and Conditions" summary="The rules and responsibilities that keep Lumyn’s products, learning services, and payments clear and fair." updated="22 June 2026" sections={sections} />; }
