import type { Metadata } from "next";
import PolicyPage, { type PolicySection } from "@/components/PolicyPage";

export const metadata: Metadata = { title: "Refund Policy", description: "Refund and cancellation terms for Lumyn Academy subscriptions and guided mentorship." };

const sections: PolicySection[] = [
  { title: "Overview", paragraphs: [<>This policy applies to payments made directly to Lumyn for Lumyn Academy and Guided Mentorship. We want payment outcomes to be predictable and will review genuine billing problems fairly.</>] },
  { title: "AI Learning Path", bullets: [<>You may request a refund of your first paid AI Learning Path charge within 7 calendar days of payment.</>, <>Eligibility may be reduced where the account has generated multiple paid-only courses or substantially used paid tutor, assessment, or certificate features after the charge.</>, <>Renewal charges should be reported within 48 hours if you intended to cancel and have not used the service after renewal. We review later requests individually.</>, <>Cancelling renewal is not itself a refund. After cancellation, access continues until the end of the paid billing period.</>] },
  { title: "Guided Mentorship", bullets: [<>A first mentorship payment may be refunded when requested within 7 calendar days of payment and at least 48 hours before the first scheduled session.</>, <>After mentorship has started, completed sessions and delivered reviews are non-refundable. We may refund an unused future portion where service cannot reasonably be delivered.</>, <>A session may be rescheduled without charge when at least 24 hours’ notice is provided. Missed sessions or late cancellations are normally non-refundable, except for emergencies reviewed case by case.</>] },
  { title: "Duplicate, incorrect, or unauthorized charges", paragraphs: [<>Duplicate or incorrect charges will be refunded after verification. If you believe a payment was unauthorized, contact us and your bank immediately. We may request information needed to investigate and may restrict the affected account while the review is ongoing.</>] },
  { title: "How to request a refund", paragraphs: [<>Submit a request through our <a href="/contact" className="font-semibold text-[#6c5ce7] underline underline-offset-4 dark:text-[#b9b1ff]">contact page</a> or email <a href="mailto:hello@lumynhq.studio" className="font-semibold text-[#6c5ce7] underline underline-offset-4 dark:text-[#b9b1ff]">hello@lumynhq.studio</a>.</>], bullets: [<>Include the account email, Paystack payment reference, plan purchased, payment date, and reason for the request.</>, <>Do not send complete card details, PINs, passwords, or one-time codes.</>] },
  { title: "Review and processing time", paragraphs: [<>We aim to acknowledge refund requests within 2 business days. Approved refunds are submitted to the original payment method through Paystack. They commonly appear within 5–10 business days after approval, but the final timing depends on Paystack, your bank, card network, and location.</>] },
  { title: "Chargebacks and contact", paragraphs: [<>Please contact us first so we can investigate quickly. This does not remove any right you have to contact your bank or payment provider. Questions may be sent to <a href="mailto:hello@lumynhq.studio" className="font-semibold text-[#6c5ce7] underline underline-offset-4 dark:text-[#b9b1ff]">hello@lumynhq.studio</a>.</>] },
];

export default function RefundPolicyPage() { return <PolicyPage eyebrow="Payments" title="Refund Policy" summary="When a Lumyn payment may be refunded, how to submit a request, and what happens after approval." updated="22 June 2026" sections={sections} />; }
